# PostgreSQL数据库配置
datasource:
  # 数据库地址
  host: localhost
  # 端口号
  port: 15432
  # 用户名
  user: postgres
  # 密码
  password: Mygvo0oq0818
  # 连接池最大数量
  max_pool_size: 30
  # 最大空闲时间（秒）
  idle_timeout: 120
  # 数据库名
  db_name: short_link

# 暂不支持集群和ssh
redis:
  host: localhost
  port: 6379
  user_name:
  password: mygvo0oq
  # 最大连接数
  max_size: 10
  # 使用的db
  database: 2